controller_manager:
  ros__parameters:
    update_rate: 100
    arm_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - Revolute 40
        - Revolute 43
        - Revolute 44
        - Revolute 45
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
