# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    pointer_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - Revolute 40
      - Revolute 43
      - Revolute 44
      - Revolute 45
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
pointer_controller:
  ros__parameters:
    joint: Revolute 45
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity